### ISSUE TITLE
swapped units in example 5.1

### ISSUE THREAD

**Issue by mjbrodzik** [marqh/ncContainers#1]
Mark--I just read through your ncContainters document (got it from Ted Habermann).  I think you may have swapped the lat/lon units for instrument__lat and instrument__lon in Example 5.1 Simple Container.

--Mary Jo Brodzik, NSIDC

**Comment by marqh** [comment]
Hello Mary

thank you for identifying this mistake, I have now updated the example to correct this
http://marqh.github.io/ncContainers/build/html/examples/simplegroup.html

mark

**Comment by mjbrodzik** [comment]
Mark--Just saw this from years ago.  Apparently I should have closed this issue myself.  Sorry for not doing so.
